export { Login , Register} from './Auth';
export {default as Root} from './Root/Root';
export {default as Route} from './Root/Root';
export {default as Admin } from './Admin/Admin';
export {default as Error } from './Error/Error';
export {default as Home } from './Home/Home';
export {default as Profil } from './Profil/Profil';
export {default as Roadmaps } from './Roadmaps/Roadmaps';
export {default as AllRoadmaps } from './AllRoadmaps/AllRoadmaps';
export {default as Roadmap } from './Roadmap/Roadmap';
export {default as EditStep } from './Step/EditStep';
export {default as ViewStep } from './Step/ViewStep';